{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "qdrant-controller.fullname" . }}-view
  labels:
    {{- include "qdrant-controller.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "qdrant.infra.doodle.com"
  resources:
  - qdrantclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "qdrant.infra.doodle.com"
  resources:
  - qdrantclusters/status
  verbs:
  - get
{{- end }}
